export const SERVER_URL = 'http://127.0.0.1:8092';
export const MARKET_LOC = {
  "us_market": "United States",
  "cn_market": "China (Mainland)",
  "hk_market": "Hong Kong",
  "gb_market": "UK",
  "sg_market": "Singapore",
  "tw_market": "Taiwan",
  "jp_market": "Japan",
  "kr_market": "South Korea",
  "ca_market": "Canada",
  "fr_market": "France",
  "de_market": "German",
  "dr_market": "German",
  "ru_market": "Russia",
  "au_market": "Australia",
  "ch_market": "Switzerland",
  "in_market": "India",
  "mx_market": "Mexico",
  "it_market": "Italy",
  "es_market": "Spain",
  "pt_market": "Portugal",
  "se_market": "Sweden",
  "sr_market": "Saudi Arabia",
  "ccc_market": "Global",
}
